name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
    - name: Install qmake
      run: sudo apt-get install qt5-default
    - run: pwd
    - run: ls -l
    - name: Makefile make
      run: qmake -o Makefile ../Calculator.pro
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
