name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.4.2'
    - uses: actions/checkout@v3
    - name: Makefile make
      run: qmake -o Makefile Calculator.pro
    - run: pwd
    - run: ls -l
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
